import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../../../core/providers/shared_prefs_provider.dart';
import '../../auth/providers/auth_providers.dart';
import '../models/timesheet_entry.dart';
import '../providers/repository_providers.dart';
import 'timesheet_controller.dart';

class ShiftState {
  final bool isClockedIn;
  final DateTime? clockInAt;
  final Duration elapsed;
  final bool onBreak;
  final DateTime? breakStartedAt;
  final Duration breakElapsed;

  const ShiftState({
    required this.isClockedIn,
    required this.clockInAt,
    required this.elapsed,
    required this.onBreak,
    required this.breakStartedAt,
    required this.breakElapsed,
  });

  const ShiftState.initial()
      : isClockedIn = false,
        clockInAt = null,
        elapsed = Duration.zero,
        onBreak = false,
        breakStartedAt = null,
        breakElapsed = Duration.zero;

  ShiftState copyWith({
    bool? isClockedIn,
    DateTime? clockInAt,
    Duration? elapsed,
    bool? onBreak,
    DateTime? breakStartedAt,
    Duration? breakElapsed,
  }) {
    return ShiftState(
      isClockedIn: isClockedIn ?? this.isClockedIn,
      clockInAt: clockInAt ?? this.clockInAt,
      elapsed: elapsed ?? this.elapsed,
      onBreak: onBreak ?? this.onBreak,
      breakStartedAt: breakStartedAt ?? this.breakStartedAt,
      breakElapsed: breakElapsed ?? this.breakElapsed,
    );
  }
}

final shiftControllerProvider =
    NotifierProvider<ShiftController, ShiftState>(ShiftController.new);

class ShiftController extends Notifier<ShiftState> {
  Timer? _timer;
  late SharedPreferences _prefs;

  String? get _employeeId => ref.watch(selectedKioskEmployeeProvider)?.id;

  String _key(String base) => '${base}_$_employeeId';

  static const _baseKeyClockInAt = 'clock_in_at';
  static const _baseKeyBreakStartedAt = 'break_started_at';
  static const _baseKeyBreakElapsed = 'break_elapsed_ms';

  @override
  ShiftState build() {
    _prefs = ref.watch(sharedPreferencesProvider);
    final employeeId = _employeeId;

    ref.onDispose(() {
      _timer?.cancel();
    });

    if (employeeId == null) {
      return const ShiftState.initial();
    }

    // Load persisted state for THIS employee
    final clockInMs = _prefs.getInt(_key(_baseKeyClockInAt));
    final breakStartedMs = _prefs.getInt(_key(_baseKeyBreakStartedAt));
    final breakElapsedMs = _prefs.getInt(_key(_baseKeyBreakElapsed)) ?? 0;

    if (clockInMs != null) {
      final clockInAt = DateTime.fromMillisecondsSinceEpoch(clockInMs);
      final breakStartedAt = breakStartedMs != null
          ? DateTime.fromMillisecondsSinceEpoch(breakStartedMs)
          : null;
      final breakElapsed = Duration(milliseconds: breakElapsedMs);

      // Schedule ticker start after build
      Future.microtask(() => _startTicker());

      return ShiftState(
        isClockedIn: true,
        clockInAt: clockInAt,
        elapsed: _calculateElapsed(clockInAt, breakElapsed, breakStartedAt),
        onBreak: breakStartedAt != null,
        breakStartedAt: breakStartedAt,
        breakElapsed: breakElapsed,
      );
    }

    return const ShiftState.initial();
  }

  void clockIn(String employeeId) {
    if (state.isClockedIn || _employeeId != employeeId) return;

    final now = DateTime.now();
    _prefs.setInt(_key(_baseKeyClockInAt), now.millisecondsSinceEpoch);

    state = state.copyWith(
      isClockedIn: true,
      clockInAt: now,
      elapsed: Duration.zero,
      onBreak: false,
      breakStartedAt: null,
      breakElapsed: Duration.zero,
    );

    _startTicker();
  }

  void clockOut(String employeeId) {
    if (!state.isClockedIn || _employeeId != employeeId) return;

    if (state.onBreak) {
      endBreak();
    }

    _timer?.cancel();
    _timer = null;

    final clockOutAt = DateTime.now();
    final clockInAt = state.clockInAt;

    if (clockInAt != null) {
      final worked = state.elapsed;

      try {
        ref.read(syncRepositoryProvider).queueEntry(
              TimesheetEntry(
                id: '', // Will be generated by Supabase
                employeeId: employeeId,
                clockIn: clockInAt,
                clockOut: clockOutAt,
                status: 'completed',
                createdAt: DateTime.now(),
                updatedAt: DateTime.now(),
                worked: worked,
                breaks: state.breakElapsed,
              ),
            );
      } catch (e) {
        debugPrint('Failed to add entry: $e');
      }
    }

    // Clear persistence
    _prefs.remove(_key(_baseKeyClockInAt));
    _prefs.remove(_key(_baseKeyBreakStartedAt));
    _prefs.remove(_key(_baseKeyBreakElapsed));

    state = const ShiftState.initial();
  }

  void startBreak() {
    if (!state.isClockedIn || state.onBreak) return;
    final now = DateTime.now();
    _prefs.setInt(_key(_baseKeyBreakStartedAt), now.millisecondsSinceEpoch);
    state = state.copyWith(onBreak: true, breakStartedAt: now);
  }

  void endBreak() {
    if (!state.isClockedIn || !state.onBreak) return;

    final started = state.breakStartedAt;
    final added =
        started == null ? Duration.zero : DateTime.now().difference(started);
    final totalBreak = state.breakElapsed + added;

    _prefs.remove(_key(_baseKeyBreakStartedAt));
    _prefs.setInt(_key(_baseKeyBreakElapsed), totalBreak.inMilliseconds);

    state = state.copyWith(
      onBreak: false,
      breakStartedAt: null,
      breakElapsed: totalBreak,
    );
  }

  void _startTicker() {
    _timer?.cancel();
    _timer = Timer.periodic(const Duration(seconds: 1), (_) {
      if (!state.isClockedIn) return;

      state = state.copyWith(
        elapsed: _calculateElapsed(
          state.clockInAt!,
          state.breakElapsed,
          state.breakStartedAt,
        ),
      );
    });
  }

  Duration _calculateElapsed(
    DateTime clockInAt,
    Duration breakElapsed,
    DateTime? breakStartedAt,
  ) {
    final raw = DateTime.now().difference(clockInAt);
    final currentBreak = breakStartedAt != null
        ? DateTime.now().difference(breakStartedAt)
        : Duration.zero;

    final effective = raw - breakElapsed - currentBreak;
    return effective.isNegative ? Duration.zero : effective;
  }
}
